In [1]:
# 1. 필용한 라이브러리를 불러온다.
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

d:\dev\workspace\ai\llm\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# 2. 모델명을 설정하고 토크나이저와 모델을 불러온다.
model_id = "Bllossom/llama-3.2-Korean-Bllossom-3B"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)

Loading weights: 100%|██████████| 254/254 [00:00<00:00, 3556.93it/s]


In [3]:
tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

In [4]:
question = "철수가 10개의 사과를 가지고 있었는데 영희가 3개를 가져가면 철수에게 남은 사과의 갯수는 몇개인가요?"
inputs = tokenizer(text=question, padding=True, return_tensors="pt")

In [5]:
print(inputs)

{'input_ids': tensor([[128000, 107837, 123503,    220,    605, 123590,  33229,  54780,  18918,
         120693, 107417, 103170, 101603, 105204,  20565,    220,     18, 117594,
          89946,  20565,  33390, 112521,  24140, 102244, 102484,  34804,  33229,
         125701,  17196,    107,  24140,  16969, 113156,  60861, 115372,  36811,
             30]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [6]:
print(inputs.input_ids)

tensor([[128000, 107837, 123503,    220,    605, 123590,  33229,  54780,  18918,
         120693, 107417, 103170, 101603, 105204,  20565,    220,     18, 117594,
          89946,  20565,  33390, 112521,  24140, 102244, 102484,  34804,  33229,
         125701,  17196,    107,  24140,  16969, 113156,  60861, 115372,  36811,
             30]])


In [7]:
print(inputs.attention_mask)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [8]:
# 5. 전처리 작업을 마친 질문을 모델에 넣어 답변 텍스트를 생성한다.
model.eval()
with torch.no_grad():
    output_ids = model.generate(
        input_ids = inputs["input_ids"],
        attention_mask = inputs["attention_mask"],        
        max_new_tokens = 100,
        do_sample = True,
        top_p = 0.9,
        temperature = 0.7
    )

[transformers] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


In [12]:
# 6. 결과를 확인할 때는 텐서 구조에서 0번째 요소를 추출하고, 사람이 읽을 수 있도록 디코딩을 한다.
result = tokenizer.decode(token_ids=output_ids[0], skip_special_tokens=True)
print(result)

철수가 10개의 사과를 가지고 있었는데 영희가 3개를 가져가면 철수에게 남은 사과의 갯수는 몇개인가요??
1) 철수가 10개의 사과를 가지고 있었고 영희가 3개를 가져가면
   철수에게 남은 사과의 갯수는 10 - 3 = 7개입니다. 
2) 철수가 10개의 사과를 가지고 있었고 영희가 3개를 가져가면
   철수에게 남은 사과의 갯수는 10 - 3 = 7개입니다. 
이 두 문장은 동일


In [14]:
print(output_ids)
print(output_ids.shape)

tensor([[128000, 107837, 123503,    220,    605, 123590,  33229,  54780,  18918,
         120693, 107417, 103170, 101603, 105204,  20565,    220,     18, 117594,
          89946,  20565,  33390, 112521,  24140, 102244, 102484,  34804,  33229,
         125701,  17196,    107,  24140,  16969, 113156,  60861, 115372,  36811,
             30,   5380,     16,      8, 112521, 123503,    220,    605, 123590,
          33229,  54780,  18918, 120693, 107417,  35495, 101603, 105204,  20565,
            220,     18, 117594,  89946,  20565,  33390,    198,    256, 112521,
          24140, 102244, 102484,  34804,  33229, 125701,  17196,    107,  24140,
          16969,    220,    605,    482,    220,     18,    284,    220,     22,
          60861,  80052,     13,    720,     17,      8, 112521, 123503,    220,
            605, 123590,  33229,  54780,  18918, 120693, 107417,  35495, 101603,
         105204,  20565,    220,     18, 117594,  89946,  20565,  33390,    198,
            256, 112521,  24